name: Merge Sort Benchmark Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ compiler and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y cmake
          sudo apt-get install -y g++
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y libboost-all-dev

      - name: Build Merge_sort_benchmark
        run: |
          mkdir build
          cd build
          cmake ..
          make Merge_sort_benchmark

      - name: Run benchmark test
        run: |
          ./build/Merge_sort_benchmark --size 100000 --iterations 10
          
      - name: Capture benchmark results
        run: |
          ./build/Merge_sort_benchmark --size 100000 --iterations 10 > benchmark_output.txt
          
      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-output
          path: benchmark_output.txt
